version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: uworx

  jiraworklogsservice:
    image: ${DOCKER_REGISTRY-}jiraworklogsservice
    build:
      context: .
      dockerfile: JiraWorkLogsService/Dockerfile

  jiraworklogswebapp:
    image: ${DOCKER_REGISTRY-}jiraworklogswebapp
    build:
      context: .
      dockerfile: JiraWorkLogsWebApp/Dockerfile

