version: '3.5'

volumes:
  database:

services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # ports:
    #   - 9411:9411

  redis:
    container_name: redis
    image: redis
    # ports:
    #   - 6379:6379

  rabbitmq: # login:password guest:guest
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    # ports: # 4369, 5671, 5672, 25672, 15671
    # - 15672:15672

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=uworx
    volumes:
      - ./database:/var/lib/postgresql

  service:
    image: ${DOCKER_REGISTRY-}service
    build:
      context: .
      dockerfile: JiraWorkLogsService/Dockerfile
    environment:
      - TZ=Asia/Karachi
      - JIRA_URL=${JIRAURL}
      - JIRA_USER=${JIRAUSER}
      - JIRA_TOKEN=${JIRATOKEN}
    depends_on:
      - zipkin
      - redis
      - rabbitmq
      - postgres

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: JiraWorkLogsWebApp/Dockerfile
    environment:
      - TZ=Asia/Karachi
    depends_on:
      - zipkin
      - redis
      - rabbitmq

  bauth:
    container_name: bauth
    build:
      context: BAuth/
    restart: unless-stopped
    environment:
      - TZ=Asia/Karachi

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - bauth
      - webapp
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80